### ISSUE TITLE
make error!

### ISSUE THREAD

**Issue by lqql2012** [errno-mmd/readfacevmd#1]
I installed the relevant lib as required，But when I execute the make instruction, I get an error at the last link，std error as below，i do not know how to resolve it ! 
[ 50%] Building CXX object CMakeFiles/readfacevmd.dir/MMDFileIOUtil.cc.o
[ 75%] Building CXX object CMakeFiles/readfacevmd.dir/VMD.cc.o
[100%] Linking CXX executable readfacevmd
/usr/local/lib/libLandmarkDetector.a(LandmarkDetectorFunc.cpp.o): In function `dlib_check_consistent_assert_usage':
LandmarkDetectorFunc.cpp:(.text.dlib_check_consistent_assert_usage[dlib_check_consistent_assert_usage]+0x6): undefined reference to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
collect2: error: ld returned 1 exit status
CMakeFiles/readfacevmd.dir/build.make:165: recipe for target 'readfacevmd' failed
make[2]: *** [readfacevmd] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/readfacevmd.dir/all' failed
make[1]: *** [CMakeFiles/readfacevmd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
note:my lib of opencv openface dlib can work alone

**Comment by errno-mmd** [comment]
I have no clue how to solve your problem.
That error doesn't occur in my environment.
I guess the error message may help you.
