### ISSUE TITLE
"too many positional options" error for GUI version

### ISSUE THREAD

**Issue by ButzYung** [errno-mmd/readfacevmd#3]
I have been trying to use the precompiled version of readfacevmd downloaded from your NicoNico video, but the GUI version always return the "too many positional options have been specificed on the command line" error. I have tried both the 32-bit and 64-bit version but they all return the same error. I have to directly use the command-line version (readfacevmd.exe) without specificying any extra option (e.g. readfacevmd _.avi _.vmd) to generate the VMD file successfully.

OS: Windows 10 Home 64-bit (version 1809)
CPU: AMD Athlon X4 860K Quad Core

**Comment by errno-mmd** [comment]
Thanks for your report. I found that readfacevmd GUI fails when the input / output file path contains a white space. I'll try to fix the problem.

**Comment by errno-mmd** [comment]
Now it should be fixed. Please try v1.1.
