### ISSUE TITLE
VMD作成ボタン押下の後にエラーとなる

### ISSUE THREAD

**Issue by Denimmddeni** [errno-mmd/readfacevmd#6]
@errno-mmd
 お世話になっております。MMD初心者です。
readfacevmd使用させていただきました。使用させていただきありがとうございます。
昨日vmdファイル作成に成功し、モデルへも使用できたことを確認いたしました。
本日別の動画ファイル（mp4）で再度作成してみようと思いましたら実行後にエラーの子画面が表示されるようになってしまいました。
※念のため昨日成功した動画（mp4）で同じことを実施しましたがやはり同じ挙動です。
誤って何かしらのファイルを削除したかもと思い、Readmeの手順（3）から再度試したのですが結果は変わりませんでした。
PCのRebootもしましたが改善されません。
readfacevmdと、OpenFace_2.2.0_win_x64を再度ダウンロードするところから再度実施してみるつもりですが
何か対処法はないかとお聞きした次第です。

＜環境＞
Win10 64bit
readfacevmd のバージョン：readfacevmd-1.8
OpenFace のバージョン：OpenFace_2.2.0_win_x64
お忙しいところ恐れ入りますがよろしくお願いいたします。
※Gitアカウントも初めて作成しましたため、何か失礼がありましたらすみません。

**Comment by errno-mmd** [comment]
何が起こっているのかを知るために、
エラーメッセージをコピー＆ペーストするか、エラーメッセージのスクリーンショットを取って見せてもらえますか？

**Comment by Denimmddeni** [comment]
@errno-mmd 
errno-mmd 様
お忙しい中、ご返信ありがとうございます。
下記となります。

宜しくお願い致します。

![スクリーンショット 2021-09-29 004913](https://user-images.githubusercontent.com/91485057/135121679-988406bd-6562-4ef0-86fb-2366ee16cf62.png)

**Comment by errno-mmd** [comment]
何もメッセージを出力できずにエラー終了しているところを見ると、
readfacevmdの32bit版を上書きコピーしてしまった可能性が考えられます。
readfacevmd-1.8 をダウンロードしてやり直したほうがいいと思います。
お使いの環境は64bit環境のようなので、「32bit」フォルダの中身は使わないようにしてください。

**Comment by Denimmddeni** [comment]
承知しました。
再度ダウンロードしてやってみます。
ありがとうございました。
